```{r}
#Loading in .csv files
Benchmarking2016 = read.csv("../Data/2016_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2017 = read.csv("../Data/2017_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2018 = read.csv("../Data/2018_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2019 = read.csv("../Data/2019_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2020 = read.csv("../Data/2020_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2021 = read.csv("../Data/2021_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2022 = read.csv("../Data/2022_Building_Energy_Benchmarking.csv", header = TRUE)

```

```{r}
#Removing columns not present in all years
Bench2016 = subset(Benchmarking2016, select = -c(Comments,Outlier,DefaultData) )
Bench2017 = subset(Benchmarking2017, select = -c(Outlier,DefaultData) )
Bench2018 = subset(Benchmarking2018, select = -c(Compliance.Issue, EPA.Building.Sub.Type.Name) )
Bench2019 = subset(Benchmarking2019, select = -c(ComplianceIssue) )
Bench2020 = subset(Benchmarking2020, select = -c(ComplianceIssue) )
Bench2021 = subset(Benchmarking2021, select = -c(ComplianceIssue) )
Bench2022 = subset(Benchmarking2022, select = -c(ComplianceIssue) )
```

```{r}
#Adding columns of NULL values
Bench2018['TaxParcelIdentificationNumber'] <- NA
Bench2018['NumberofBuildings'] <- NA
Bench2018['YearsENERGYSTARCertified'] <- NA
Bench2018['ListOfAllPropertyUseTypes'] <- NA
Bench2019['YearsENERGYSTARCertified'] <- NA
Bench2019['NumberofBuildings'] <- NA
Bench2019['ListOfAllPropertyUseTypes'] <- NA
Bench2020['YearsENERGYSTARCertified'] <- NA
Bench2020['ListOfAllPropertyUseTypes'] <- NA
Bench2021['YearsENERGYSTARCertified'] <- NA
Bench2021['ListOfAllPropertyUseTypes'] <- NA
Bench2022['YearsENERGYSTARCertified'] <- NA
Bench2022['ListOfAllPropertyUseTypes'] <- NA

```

```{r}
#Renaming columns in 2018 so that naming conventions match other years
names(Bench2018)[1] <- "OSEBuildingID"
names(Bench2018)[2] <- "DataYear"
names(Bench2018)[3] <- "PropertyName"
names(Bench2018)[4] <- "BuildingType"
names(Bench2018)[8] <- "ZipCode"
names(Bench2018)[12] <- "CouncilDistrictCode"
names(Bench2018)[13] <- "YearBuilt"
names(Bench2018)[14] <- "NumberofFloors"
names(Bench2018)[15] <- "PropertyGFATotal"
names(Bench2018)[17] <- "PropertyGFAParking"
names(Bench2018)[18] <- "PrimaryPropertyType"
names(Bench2018)[19] <- "ENERGYSTARScore"
names(Bench2018)[26] <- "LargestPropertyUseType"
names(Bench2018)[27] <- "LargestPropertyUseTypeGFA"
names(Bench2018)[28] <- "SecondLargestPropertyUseType"
names(Bench2018)[29] <- "SecondLargestPropertyUseTypeGFA"
names(Bench2018)[30] <- "ThirdLargestPropertyUseType"
names(Bench2018)[31] <- "ThirdLargestPropertyUseTypeGFA"
names(Bench2018)[35] <- "ComplianceStatus"
names(Bench2018)[38] <- "GHGEmissionsIntensity"
names(Bench2018)[39] <- "TotalGHGEmissions"

```

```{r}
#Renaming columns between the years of data with conventions that do not match
names(Bench2019)[3] <- "PropertyName"
names(Bench2020)[3] <- "PropertyName"
names(Bench2020)[27] <- "PrimaryPropertyType"
names(Bench2021)[3] <- "PropertyName"
names(Bench2021)[27] <- "PrimaryPropertyType"
names(Bench2022)[3] <- "PropertyName"
names(Bench2022)[27] <- "PrimaryPropertyType"
```

```{r}
#Specifying the order of the columns
col_order <- c("OSEBuildingID", "DataYear", "BuildingType", "PrimaryPropertyType",
               "PropertyName", "Address", "City", "State",
               "ZipCode", "TaxParcelIdentificationNumber", "CouncilDistrictCode", "Neighborhood",
               "Latitude", "Longitude", "YearBuilt", "NumberofBuildings",
               "NumberofFloors", "PropertyGFATotal", "PropertyGFAParking", "PropertyGFABuilding.s.",
               "ListOfAllPropertyUseTypes", "LargestPropertyUseType", "LargestPropertyUseTypeGFA", "SecondLargestPropertyUseType",
               "SecondLargestPropertyUseTypeGFA", "ThirdLargestPropertyUseType", "ThirdLargestPropertyUseTypeGFA", "YearsENERGYSTARCertified",
               "ENERGYSTARScore", "SiteEUI.kBtu.sf.", "SiteEUIWN.kBtu.sf.", "SourceEUI.kBtu.sf.",
               "SourceEUIWN.kBtu.sf.", "SiteEnergyUse.kBtu.", "SiteEnergyUseWN.kBtu.", "SteamUse.kBtu.",
               "Electricity.kWh.", "Electricity.kBtu.", "NaturalGas.therms.", "NaturalGas.kBtu.",
               "ComplianceStatus", "TotalGHGEmissions", "GHGEmissionsIntensity")
```

```{r}
#Changing the order of the columns so that they are consistent
Bench2016 <- Bench2016[,col_order]
Bench2017 <- Bench2017[,col_order]
Bench2018 <- Bench2018[,col_order]
Bench2019 <- Bench2019[,col_order]
Bench2020 <- Bench2020[,col_order]
Bench2021 <- Bench2021[,col_order]
Bench2022 <- Bench2022[,col_order]
```


```{r}
#Binding data years together
Bound2016_17 = rbind(Bench2016, Bench2017)
Bound2016_18 = rbind(Bench2016, Bench2018)
Bound2016_19 = rbind(Bench2016, Bench2019)
Bound2016_20 = rbind(Bench2016, Bench2020)
Bound2016_21 = rbind(Bench2016, Bench2021)
Bench2016_22 = rbind(Bench2016, Bench2022)
```

```{r}
#Looking for NULL values
null_counts <- colSums(is.na(Bench2016_22))

print(null_counts)
```
```{r}
#Removed columns with too many NULL values to make the variable usable. 
Bench_cleaned = subset(Bench2016_22, select = -c(ListOfAllPropertyUseTypes, SecondLargestPropertyUseType, SecondLargestPropertyUseTypeGFA, ThirdLargestPropertyUseType, ThirdLargestPropertyUseTypeGFA, YearsENERGYSTARCertified, ENERGYSTARScore, SteamUse.kBtu., NaturalGas.therms., NaturalGas.kBtu.) )
```


```{r}
#Substituted NULL values with the column mean (for now)
Bench_cleaned <- Bench_cleaned %>% mutate(NumberofBuildings = ifelse(is.na(NumberofBuildings), 1.122, NumberofBuildings))
Bench_cleaned <- Bench_cleaned %>% mutate(LargestPropertyUseTypeGFA = ifelse(is.na(LargestPropertyUseTypeGFA), 82861, LargestPropertyUseTypeGFA))
Bench_cleaned <- Bench_cleaned %>% mutate(SiteEUI.kBtu.sf. = ifelse(is.na(SiteEUI.kBtu.sf.), 53.61, SiteEUI.kBtu.sf.))
Bench_cleaned <- Bench_cleaned %>% mutate(SiteEUIWN.kBtu.sf. = ifelse(is.na(SiteEUIWN.kBtu.sf.), 54.20, SiteEUIWN.kBtu.sf.))
Bench_cleaned <- Bench_cleaned %>% mutate(SourceEUI.kBtu.sf. = ifelse(is.na(SourceEUI.kBtu.sf.), 125.1, SourceEUI.kBtu.sf.))
Bench_cleaned <- Bench_cleaned %>% mutate(SourceEUIWN.kBtu.sf. = ifelse(is.na(SourceEUIWN.kBtu.sf.), 125.9, SourceEUIWN.kBtu.sf.))
Bench_cleaned <- Bench_cleaned %>% mutate(SiteEnergyUse.kBtu. = ifelse(is.na(SiteEnergyUse.kBtu.), 5589121, SiteEnergyUse.kBtu.))
Bench_cleaned <- Bench_cleaned %>% mutate(SiteEnergyUseWN.kBtu. = ifelse(is.na(SiteEnergyUseWN.kBtu.), 5434499, SiteEnergyUseWN.kBtu.))
Bench_cleaned <- Bench_cleaned %>% mutate(Electricity.kWh. = ifelse(is.na(Electricity.kWh.), 1065563, Electricity.kWh.))
Bench_cleaned <- Bench_cleaned %>% mutate(Electricity.kBtu. = ifelse(is.na(Electricity.kBtu.), 3635701, Electricity.kBtu.))
Bench_cleaned <- Bench_cleaned %>% mutate(TotalGHGEmissions = ifelse(is.na(TotalGHGEmissions), 120.06, TotalGHGEmissions))
Bench_cleaned <- Bench_cleaned %>% mutate(GHGEmissionsIntensity = ifelse(is.na(GHGEmissionsIntensity), 1.111, GHGEmissionsIntensity))

null_counts_new <- colSums(is.na(Bench_cleaned))
null_counts_new

```
```{r}
#Using summary to look for NULLs and outliers
summary(Bench_cleaned)
```


```{r}
# Create boxplots to look for Outliers
boxplot(Bench_cleaned[, "CouncilDistrictCode"], col = "red", main = "Boxplot for Council District Code")
boxplot(Bench_cleaned[, "YearBuilt"], col = "blue", main = "Boxplot of Year Building was Built")
boxplot(Bench_cleaned[, "NumberofBuildings"], col = "black", main = "Boxplot of Number of Buildings")
boxplot(Bench_cleaned[, "NumberofFloors"], col = "orange", main = "Boxplot of Number of Floors")
boxplot(Bench_cleaned[, "PropertyGFATotal"], col = "purple", main = "Boxplot of Property Gross Floor Area")
boxplot(Bench_cleaned[, "PropertyGFAParking"], col = "purple", main = "Boxplot of Gross Floor Area for Parking")
boxplot(Bench_cleaned[, "PropertyGFABuilding.s."], col = "purple", main = "Boxplot of Enclosed Gross Floor Area")
boxplot(Bench_cleaned[, c("SiteEUI.kBtu.sf.", "SiteEUIWN.kBtu.sf.")], 
        col = "cyan", 
        main = "Boxplots of Site Energy Use Intensity(EUI) and Adjusted EUI",
        names = c("SiteEUI.kBtu.sf.", "SiteEUIWN.kBtu.sf."))
boxplot(Bench_cleaned[, c("SiteEUI.kBtu.sf.", "SiteEUIWN.kBtu.sf.")], 
        col = "darkgreen", 
        main = "Boxplots of Source Energy Use Intensity(EUI) and Adjusted EUI",
        names = c("SourceEUI.kBtu.sf.", "SourceEUIWN.kBtu.sf."))
boxplot(Bench_cleaned[, c("SiteEnergyUse.kBtu.", "SiteEUIWN.kBtu.sf.")], 
        col = "yellow", 
        main = "Site Energy Use and Site Energy Use Normalized",
        names = c("SiteEnergyUse.kBtu.", "SiteEnergyUseWN.kBtu."))
boxplot(Bench_cleaned[, "Electricity.kWh."], col = "aquamarine", main = "Electricty Consumed on Site in Kilowatts")
boxplot(Bench_cleaned[, "TotalGHGEmissions"], col = "deeppink", main = "Total Amount of Greenhouse Gas Emissions")
boxplot(Bench_cleaned[, "GHGEmissionsIntensity"], col = "blue3", main = "Greenhouse Gas Emissions Intensity")
```

```{r}
#Creating matrix to look for correlation
Bench_numerical <- Bench_cleaned[, c("CouncilDistrictCode", "YearBuilt", "NumberofBuildings", 
                                   "NumberofFloors", "PropertyGFATotal", "PropertyGFAParking", 
                                   "PropertyGFABuilding.s.", "SiteEUI.kBtu.sf.", "SiteEUIWN.kBtu.sf.", 
                                   "SourceEUI.kBtu.sf.", "SourceEUIWN.kBtu.sf.", "SiteEnergyUse.kBtu.", 
                                   "SiteEnergyUseWN.kBtu.", "Electricity.kWh.", "Electricity.kBtu.", 
                                   "TotalGHGEmissions", "GHGEmissionsIntensity")]


correlation_matrix <- cor(Bench_numerical)
print(correlation_matrix)
```

```{r}
#Creating heatmap to visualize correlation
correlation_matrix <- cor(Bench_numerical)

heatmap(correlation_matrix, 
        col = colorRampPalette(c("blue", "white", "red"))(100),
        scale = "none",
        symm = TRUE,  
        main = "Correlation Heatmap of Quantfiable Variables")
```

```{r}
options(repr.plot.width=10, repr.plot.height=8)  # Adjust as needed


par(mfrow = c(3, 3))  # Arrange plots in a 3x3 grid
hist(Bench_cleaned$CouncilDistrictCode, main = "Council District Code", xlab = "District Code", col = "aquamarine")
hist(Bench_cleaned$YearBuilt, main = "Year Built", xlab = "Year", col = "aquamarine")
hist(Bench_cleaned$NumberofBuildings, main = "Number of Buildings", xlab = "Number of Buildings", col = "aquamarine")
hist(Bench_cleaned$NumberofFloors, main = "Number of Floors", xlab = "Number of Floors", col = "aquamarine")
hist(Bench_cleaned$PropertyGFATotal, main = "Property Gross Floor Area", xlab = "Area", col = "aquamarine")
hist(Bench_cleaned$PropertyGFAParking, main = "Property GF Area for Parking", xlab = "Area", col = "aquamarine")
hist(Bench_cleaned$PropertyGFABuilding.s., main = "Property GFA Building", xlab = "Area", col = "aquamarine")
hist(Bench_cleaned$SiteEUI.kBtu.sf., main = "Site Energy Use Intensity", xlab = "Intensity (kBtu/sf)", col = "aquamarine")
hist(Bench_cleaned$SiteEUIWN.kBtu.sf., main = "Site Energy Use Intensity (WN)", xlab = "Intensity (kBtu/sf)", col = "aquamarine")
hist(Bench_cleaned$SourceEUI.kBtu.sf., main = "Source Energy Use Intensity", xlab = "Intensity (kBtu/sf)", col = "aquamarine")
hist(Bench_cleaned$SourceEUIWN.kBtu.sf., main = "Source Energy Use Intensity (WN)", xlab = "Intensity (kBtu/sf)", col = "aquamarine")
hist(Bench_cleaned$SiteEnergyUse.kBtu., main = "Site Energy Use", xlab = "Energy Use (kBtu)", col = "aquamarine")
hist(Bench_cleaned$SiteEnergyUseWN.kBtu., main = "Site Energy Use (WN)", xlab = "Energy Use (kBtu)", col = "aquamarine")
hist(Bench_cleaned$Electricity.kWh., main = "Electricity Use (kWh)", xlab = "Electricity Use (kWh)", col = "aquamarine")
hist(Bench_cleaned$Electricity.kBtu., main = "Electricity Use (kBtu)", xlab = "Electricity Use (kBtu)", col = "aquamarine")
hist(Bench_cleaned$TotalGHGEmissions, main = "Total GHG Emissions", xlab = "GHG Emissions", col = "aquamarine")
hist(Bench_cleaned$GHGEmissionsIntensity, main = "GHG Emissions Intensity", xlab = "Intensity", col = "aquamarine")

par(mfrow = c(1, 1))
```




