---
title: "Connor"
output: pdf_document
date: "2024-04-01"
---

```{r}
install.packages("tidyverse")
install.packages("dplyr")
library(tidyverse)
library(dplyr)
library(ggplot2)
```


```{r}
#Loading in .csv files
Benchmarking2016 <- read.csv("../Data/2016_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2017 <- read.csv("../Data/2017_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2018 <- read.csv("../Data/2018_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2019 <- read.csv("../Data/2019_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2020 <- read.csv("../Data/2020_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2021 <- read.csv("../Data/2021_Building_Energy_Benchmarking.csv", header = TRUE)
Benchmarking2022 <- read.csv("../Data/2022_Building_Energy_Benchmarking.csv", header = TRUE)

#Removing columns that are not available for year over year analysis
Bench2016 <- subset(Benchmarking2016, select = -c(Comments,Outlier,DefaultData) )
Bench2017 <- subset(Benchmarking2017, select = -c(Outlier,DefaultData) )
Bench2018 <- subset(Benchmarking2018, select = -c(Compliance.Issue, EPA.Building.Sub.Type.Name) )
Bench2019 <- subset(Benchmarking2019, select = -c(ComplianceIssue) )
Bench2020 <- subset(Benchmarking2020, select = -c(ComplianceIssue) )
Bench2021 <- subset(Benchmarking2021, select = -c(ComplianceIssue) )
Bench2022 <- subset(Benchmarking2022, select = -c(ComplianceIssue) )
```

```{r}
#read in the data here for 2016-2022
library(dplyr)
data2022 <- read.csv("../Data/Performance_Ranges_by_Building_Type_2022.csv")
data2021 <- read.csv("../Data/Performance_Ranges_by_Building_Type_2021.csv")
data2020 <- read.csv("../Data/Performance_Ranges_by_Building_Type_2020.csv")
data2019 <- read.csv("../Data/Performance_Ranges_By_Building_Type_2019.csv")
data2018 <- read.csv("../Data/Performance_Ranges_By_Building_Type_2018.csv")
data2017 <- read.csv("../Data/Performance_Ranges_by_Building_Type_2017.csv")
data2016 <- read.csv("../Data/Performance_Ranges_By_Building_Type_2016.csv")


#For 2017 specifically there are 2 columns that were giving us issues for data cleaning immediately.
#Other than 2017 we are just omitting files that have na values
data2017 <- select(data2017, -c(Low.Outlier.Cutoff, High.Outlier.Cutoff))
data2022 <- na.omit(data2022)
data2021 <- na.omit(data2021)
data2020 <- na.omit(data2020)
data2019 <- na.omit(data2019)
data2018 <- na.omit(data2018)
data2017 <- na.omit(data2017)
data2016 <- na.omit(data2016)
```

```{r}
#we are adding a year column to every dataset 
data2022 <- mutate(data2022, Year = 2022)
data2021 <- mutate(data2021, Year = 2021)
data2020 <- mutate(data2020, Year = 2020)
data2019 <- mutate(data2019, Year = 2019)
data2018 <- mutate(data2018, Year = 2018)
data2017 <- mutate(data2017, Year = 2017)
data2016 <- mutate(data2016, Year = 2016)
```


```{r}
sum_EUI_2022 <- Bench2022 %>%
  filter(!is.na(SourceEUI.kBtu.sf.)) %>%
  group_by(LargestPropertyUseType) %>% 
  summarize(count = n(), Median_Source_EUI = median(SourceEUI.kBtu.sf., na.rm = TRUE)) %>%
  filter(count > 10) %>%
  rename(BuildingType = LargestPropertyUseType) %>%
  mutate(Year = 2022)

sum_EUI_2021 <- Bench2021 %>%
  filter(!is.na(SourceEUI.kBtu.sf.)) %>%
  group_by(LargestPropertyUseType) %>% 
  summarize(count = n(), Median_Source_EUI = median(SourceEUI.kBtu.sf., na.rm = TRUE)) %>%
  filter(count > 10) %>%
  rename(BuildingType = LargestPropertyUseType) %>%
  mutate(Year = 2021)

sum_EUI_2020 <- Bench2020 %>%
  filter(!is.na(SourceEUI.kBtu.sf.)) %>%
  group_by(LargestPropertyUseType) %>% 
  summarize(count = n(), Median_Source_EUI = median(SourceEUI.kBtu.sf., na.rm = TRUE)) %>%
  filter(count > 10) %>%
  rename(BuildingType = LargestPropertyUseType) %>%
  mutate(Year = 2020)

sum_EUI_2019 <- Bench2019 %>%
  filter(!is.na(SourceEUI.kBtu.sf.)) %>%
  group_by(LargestPropertyUseType) %>% 
  summarize(count = n(), Median_Source_EUI = median(SourceEUI.kBtu.sf., na.rm = TRUE)) %>%
  filter(count > 10) %>%
  rename(BuildingType = LargestPropertyUseType) %>%
  mutate(Year = 2019)

sum_EUI_2018 <- Bench2018 %>%
  filter(!is.na(SourceEUI.kBtu.sf.)) %>%
  group_by(Largest.Property.Use.Type) %>% 
  summarize(count = n(), Median_Source_EUI = median(SourceEUI.kBtu.sf., na.rm = TRUE)) %>%
  filter(count > 10) %>%
  rename(BuildingType = Largest.Property.Use.Type) %>%
  mutate(Year = 2018)

sum_EUI_2017 <- Bench2017 %>%
  filter(!is.na(SourceEUI.kBtu.sf.)) %>%
  group_by(LargestPropertyUseType) %>% 
  summarize(count = n(), Median_Source_EUI = median(SourceEUI.kBtu.sf., na.rm = TRUE)) %>%
  filter(count > 10) %>%
  rename(BuildingType = LargestPropertyUseType) %>%
  mutate(Year = 2017)

sum_EUI_2016 <- Bench2016 %>%
  filter(!is.na(SourceEUI.kBtu.sf.)) %>%
  group_by(LargestPropertyUseType) %>% 
  summarize(count = n(), Median_Source_EUI = median(SourceEUI.kBtu.sf., na.rm = TRUE)) %>%
  filter(count > 10) %>%
  rename(BuildingType = LargestPropertyUseType) %>%
  mutate(Year = 2016)
```

```{r}
combined_sum_EUI <- bind_rows(sum_EUI_2022, sum_EUI_2021, sum_EUI_2020, sum_EUI_2019, sum_EUI_2018, sum_EUI_2017, sum_EUI_2016)


combined_stores <- combined_sum_EUI %>% 
  filter(BuildingType %in% c("Supermarket", "Supermarket/Grocery Store"))
```

```{r}
ggplot(combined_stores, aes(x = Year, y = Median_Source_EUI)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Median Source EUI", title = "Median Source EUI 2016-2022") +
  scale_x_continuous(breaks = unique(combined_stores$Year))
```


```{r}
top_quan2022 = quantile(sum_EUI_2022$Median_Source_EUI,0.75)
high_impact_buildings_2022 = sum_EUI_2022 %>%
  filter(Median_Source_EUI >= top_quan2022)%>%
  arrange(desc(Median_Source_EUI))

ggplot(high_impact_buildings_2022, aes(x = reorder(BuildingType, -Median_Source_EUI), y = Median_Source_EUI)) +
  geom_bar(stat = "identity", fill = "dodgerblue3") +
  labs(
    x = NULL,
    y = "Median Source EUI",
    title = "High-Impact Building Types Based on Median Source EUI",
    subtitle = "EUI: Energy use intensity measured per unit of floor area",
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 10),
    plot.caption = element_text(hjust = 0.5, size = 8)
  ) +
  scale_y_continuous(labels = scales::comma) # This will add commas to y-axis labels for readability
```
```{r}
ggplot(high_impact_buildings_2022, aes(x = reorder(BuildingType, -Median_Source_EUI), y = Median_Source_EUI)) +
  geom_bar(stat = "identity", fill = ifelse(high_impact_buildings_2022$BuildingType == "Supermarket/Grocery Store", "red", "dodgerblue3")) +
  labs(
    x = NULL,
    y = "Median Source EUI",
    title = "High-Impact Building Types Based on Median Source EUI",
    subtitle = "EUI: Energy use intensity measured per unit of floor area",
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 10),
    plot.caption = element_text(hjust = 0.5, size = 8)
  ) +
  scale_y_continuous(labels = scales::comma) # This will add commas to y-axis labels for readability
```


```{r}

stores2022 = Bench2022 %>% filter(EPAPropertyType == "Supermarket/Grocery Store")

stores2022 = stores2022 %>% select(OSEBuildingID,BuildingName,Address,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding.s.,ENERGYSTARScore,SiteEUIWN.kBtu.sf.,SiteEnergyUseWN.kBtu.,SourceEUIWN.kBtu.sf.,Electricity.kWh.,Electricity.kBtu.,NaturalGas.therms.,NaturalGas.kBtu.,ComplianceStatus,TotalGHGEmissions,GHGEmissionsIntensity)

s2022 = stores2022 %>% select(OSEBuildingID,BuildingName,PropertyGFATotal,ENERGYSTARScore,SourceEUIWN.kBtu.sf.) %>%
  filter(!is.na(SourceEUIWN.kBtu.sf.))

target_stores = s2022 %>% filter(ENERGYSTARScore < 80)
```


```{r}
stores_source_EUI = sum(stores2022$SourceEUIWN.kBtu.sf.,na.rm = TRUE)
all_source_EUI = sum(Bench2022$SourceEUIWN.kBtu.sf.,na.rm = TRUE)
max_reduc = stores_source_EUI * 0.4
perc_reduc = (max_reduc / all_source_EUI) * 100
perc_reduc
```
If grocery stores can reduce energy use by 40 percent, It would result in 1.5% total energy use reduction for the entire city of Seattle across all building types

```{r}
target_stores_EUI = sum(target_stores$SourceEUIWN.kBtu.sf.)
target_reduc = target_stores_EUI * 0.4
target_perc_reduc = (target_reduc / all_source_EUI) * 100
target_perc_reduc
```
Even if we did it in only the target stores (under 80 ES score or no significant improvement in energy reduction over the last few years) then it would still be almost 1% across the entire City of Seattle

```{r}
s2022 = s2022 %>% mutate(Adj_EUI = SourceEUIWN.kBtu.sf. - (SourceEUIWN.kBtu.sf.* 0.40))

```

```{r}
reduced_data2022 = sum_EUI_2022 %>%
  mutate(Median_Source_EUI = ifelse(BuildingType == "Supermarket/Grocery Store", 
                                 Median_Source_EUI * 0.6, 
                                 Median_Source_EUI))

```

```{r}
reduced_top_quan2022 = quantile(reduced_data2022$Median_Source_EUI,0.75)
reduced_high_impact_buildings_2022 = reduced_data2022 %>%
  filter(Median_Source_EUI >= reduced_top_quan2022)%>%
  arrange(desc(Median_Source_EUI))

ggplot(reduced_high_impact_buildings_2022, aes(x = reorder(BuildingType, -Median_Source_EUI), y = Median_Source_EUI)) +
  geom_bar(stat = "identity", fill = "dodgerblue3") +
  labs(
    x = NULL,
    y = "Median Source EUI",
    title = "High-Impact Building Types Based on Median Source EUI",
    subtitle = "EUI: Energy use intensity measured per unit of floor area",
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 10),
    plot.caption = element_text(hjust = 0.5, size = 8)
  ) +
  scale_y_continuous(labels = scales::comma)
```

```{r}
ggplot(reduced_high_impact_buildings_2022, aes(x = reorder(BuildingType, -Median_Source_EUI), y = Median_Source_EUI)) +
  geom_bar(stat = "identity", fill = ifelse(reduced_high_impact_buildings_2022$BuildingType == "Supermarket/Grocery Store", "red", "dodgerblue3")) +
  labs(
    x = NULL,
    y = "Median Source EUI",
    title = "High-Impact Building Types Based on Median Source EUI",
    subtitle = "EUI: Energy use intensity measured per unit of floor area",
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 10),
    plot.caption = element_text(hjust = 0.5, size = 8)
  ) +
  scale_y_continuous(labels = scales::comma)
```


```{r}
reduced_combined_stores = combined_stores %>%
  mutate(Median_Source_EUI = ifelse(Year == 2022, 
                                 Median_Source_EUI * 0.6, 
                                 Median_Source_EUI))
```

```{r}
ggplot(reduced_combined_stores, aes(x = Year, y = Median_Source_EUI)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Median Source EUI", title = "Median Source EUI 2016-2022") +
  scale_x_continuous(breaks = unique(reduced_combined_stores$Year))
```

















